security-scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install bandit
  - name: Scan with bandit
    run: |
      # Run a comprehensive security scan with detailed output
      bandit -r . -x ./tests,./venv -f txt -o bandit-output.txt
      # Check the return code - bandit returns non-zero if issues are found
      if [ $? -ne 0 ]; then
        echo "Security issues found. See bandit-output.txt for details."
        # Show the issues but don't fail the build yet (make this stricter later)
        cat bandit-output.txt
        # Return success for now to allow the workflow to continue
        exit 0
      fi
  - name: Upload security scan results
    uses: actions/upload-artifact@v3
    with:
      name: security-scan-results
      path: bandit-output.txt