security-scan:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install bandit
  - name: Scan with bandit
    run: |
      # Use the --exit-zero flag to ensure the job doesn't fail on detected issues
      bandit -r . -x ./tests,./venv --exit-zero -f txt -o bandit-output.txt
      
      # Display the output for review
      echo "Security scan completed. Results below (job will not fail):"
      cat bandit-output.txt
  - name: Upload security scan results
    uses: actions/upload-artifact@v3
    with:
      name: security-scan-results
      path: bandit-output.txt